// Code generated by entc, DO NOT EDIT.

package subitem

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the subitem type in the database.
	Label = "sub_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldLink holds the string denoting the link field in the database.
	FieldLink = "link"

	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"

	// Table holds the table name of the subitem in the database.
	Table = "sub_items"
	// ParentTable is the table the holds the parent relation/edge.
	ParentTable = "sub_items"
	// ParentInverseTable is the table name for the BagItem entity.
	// It exists in this package in order to avoid circular dependency with the "bagitem" package.
	ParentInverseTable = "bag_items"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "bag_item_sub_items"
)

// Columns holds all SQL columns for subitem fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldIcon,
	FieldLink,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the SubItem type.
var ForeignKeys = []string{
	"bag_item_sub_items",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// IconValidator is a validator for the "icon" field. It is called by the builders before save.
	IconValidator func(string) error
	// LinkValidator is a validator for the "link" field. It is called by the builders before save.
	LinkValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
