// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BagsColumns holds the columns for the "bags" table.
	BagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "icon", Type: field.TypeString, Size: 255},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// BagsTable holds the schema information for the "bags" table.
	BagsTable = &schema.Table{
		Name:        "bags",
		Columns:     BagsColumns,
		PrimaryKey:  []*schema.Column{BagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "bag_user_id_name",
				Unique:  true,
				Columns: []*schema.Column{BagsColumns[3], BagsColumns[1]},
			},
		},
	}
	// BagItemsColumns holds the columns for the "bag_items" table.
	BagItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "icon", Type: field.TypeString},
		{Name: "link", Type: field.TypeString},
		{Name: "image", Type: field.TypeString},
		{Name: "bag_items", Type: field.TypeUUID, Nullable: true},
	}
	// BagItemsTable holds the schema information for the "bag_items" table.
	BagItemsTable = &schema.Table{
		Name:       "bag_items",
		Columns:    BagItemsColumns,
		PrimaryKey: []*schema.Column{BagItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "bag_items_bags_items",
				Columns: []*schema.Column{BagItemsColumns[6]},

				RefColumns: []*schema.Column{BagsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SharesColumns holds the columns for the "shares" table.
	SharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "item_id", Type: field.TypeUUID},
	}
	// SharesTable holds the schema information for the "shares" table.
	SharesTable = &schema.Table{
		Name:        "shares",
		Columns:     SharesColumns,
		PrimaryKey:  []*schema.Column{SharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "share_user_id_item_id",
				Unique:  true,
				Columns: []*schema.Column{SharesColumns[1], SharesColumns[2]},
			},
		},
	}
	// SubItemsColumns holds the columns for the "sub_items" table.
	SubItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "icon", Type: field.TypeString},
		{Name: "link", Type: field.TypeString},
		{Name: "bag_item_sub_items", Type: field.TypeUUID, Nullable: true},
	}
	// SubItemsTable holds the schema information for the "sub_items" table.
	SubItemsTable = &schema.Table{
		Name:       "sub_items",
		Columns:    SubItemsColumns,
		PrimaryKey: []*schema.Column{SubItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "sub_items_bag_items_sub_items",
				Columns: []*schema.Column{SubItemsColumns[5]},

				RefColumns: []*schema.Column{BagItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BagsTable,
		BagItemsTable,
		SharesTable,
		SubItemsTable,
	}
)

func init() {
	BagItemsTable.ForeignKeys[0].RefTable = BagsTable
	SubItemsTable.ForeignKeys[0].RefTable = BagItemsTable
}
