// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"web-stash-api/ent/bagitem"
	"web-stash-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BagItemDelete is the builder for deleting a BagItem entity.
type BagItemDelete struct {
	config
	hooks    []Hook
	mutation *BagItemMutation
}

// Where adds a new predicate to the BagItemDelete builder.
func (bid *BagItemDelete) Where(ps ...predicate.BagItem) *BagItemDelete {
	bid.mutation.predicates = append(bid.mutation.predicates, ps...)
	return bid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bid *BagItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bid.hooks) == 0 {
		affected, err = bid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BagItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bid.mutation = mutation
			affected, err = bid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bid.hooks) - 1; i >= 0; i-- {
			mut = bid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (bid *BagItemDelete) ExecX(ctx context.Context) int {
	n, err := bid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bid *BagItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: bagitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: bagitem.FieldID,
			},
		},
	}
	if ps := bid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, bid.driver, _spec)
}

// BagItemDeleteOne is the builder for deleting a single BagItem entity.
type BagItemDeleteOne struct {
	bid *BagItemDelete
}

// Exec executes the deletion query.
func (bido *BagItemDeleteOne) Exec(ctx context.Context) error {
	n, err := bido.bid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bagitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bido *BagItemDeleteOne) ExecX(ctx context.Context) {
	bido.bid.ExecX(ctx)
}
