// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"
	"web-stash-api/ent/bag"
	"web-stash-api/ent/bagitem"
	"web-stash-api/ent/predicate"
	"web-stash-api/ent/subitem"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BagItemQuery is the builder for querying BagItem entities.
type BagItemQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.BagItem
	// eager-loading edges.
	withBag      *BagQuery
	withSubItems *SubItemQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BagItemQuery builder.
func (biq *BagItemQuery) Where(ps ...predicate.BagItem) *BagItemQuery {
	biq.predicates = append(biq.predicates, ps...)
	return biq
}

// Limit adds a limit step to the query.
func (biq *BagItemQuery) Limit(limit int) *BagItemQuery {
	biq.limit = &limit
	return biq
}

// Offset adds an offset step to the query.
func (biq *BagItemQuery) Offset(offset int) *BagItemQuery {
	biq.offset = &offset
	return biq
}

// Order adds an order step to the query.
func (biq *BagItemQuery) Order(o ...OrderFunc) *BagItemQuery {
	biq.order = append(biq.order, o...)
	return biq
}

// QueryBag chains the current query on the "bag" edge.
func (biq *BagItemQuery) QueryBag() *BagQuery {
	query := &BagQuery{config: biq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := biq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := biq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bagitem.Table, bagitem.FieldID, selector),
			sqlgraph.To(bag.Table, bag.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bagitem.BagTable, bagitem.BagColumn),
		)
		fromU = sqlgraph.SetNeighbors(biq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubItems chains the current query on the "sub_items" edge.
func (biq *BagItemQuery) QuerySubItems() *SubItemQuery {
	query := &SubItemQuery{config: biq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := biq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := biq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bagitem.Table, bagitem.FieldID, selector),
			sqlgraph.To(subitem.Table, subitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, bagitem.SubItemsTable, bagitem.SubItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(biq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BagItem entity from the query.
// Returns a *NotFoundError when no BagItem was found.
func (biq *BagItemQuery) First(ctx context.Context) (*BagItem, error) {
	nodes, err := biq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bagitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (biq *BagItemQuery) FirstX(ctx context.Context) *BagItem {
	node, err := biq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BagItem ID from the query.
// Returns a *NotFoundError when no BagItem ID was found.
func (biq *BagItemQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = biq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bagitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (biq *BagItemQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := biq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BagItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one BagItem entity is not found.
// Returns a *NotFoundError when no BagItem entities are found.
func (biq *BagItemQuery) Only(ctx context.Context) (*BagItem, error) {
	nodes, err := biq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bagitem.Label}
	default:
		return nil, &NotSingularError{bagitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (biq *BagItemQuery) OnlyX(ctx context.Context) *BagItem {
	node, err := biq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BagItem ID in the query.
// Returns a *NotSingularError when exactly one BagItem ID is not found.
// Returns a *NotFoundError when no entities are found.
func (biq *BagItemQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = biq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = &NotSingularError{bagitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (biq *BagItemQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := biq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BagItems.
func (biq *BagItemQuery) All(ctx context.Context) ([]*BagItem, error) {
	if err := biq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return biq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (biq *BagItemQuery) AllX(ctx context.Context) []*BagItem {
	nodes, err := biq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BagItem IDs.
func (biq *BagItemQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := biq.Select(bagitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (biq *BagItemQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := biq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (biq *BagItemQuery) Count(ctx context.Context) (int, error) {
	if err := biq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return biq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (biq *BagItemQuery) CountX(ctx context.Context) int {
	count, err := biq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (biq *BagItemQuery) Exist(ctx context.Context) (bool, error) {
	if err := biq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return biq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (biq *BagItemQuery) ExistX(ctx context.Context) bool {
	exist, err := biq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BagItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (biq *BagItemQuery) Clone() *BagItemQuery {
	if biq == nil {
		return nil
	}
	return &BagItemQuery{
		config:       biq.config,
		limit:        biq.limit,
		offset:       biq.offset,
		order:        append([]OrderFunc{}, biq.order...),
		predicates:   append([]predicate.BagItem{}, biq.predicates...),
		withBag:      biq.withBag.Clone(),
		withSubItems: biq.withSubItems.Clone(),
		// clone intermediate query.
		sql:  biq.sql.Clone(),
		path: biq.path,
	}
}

// WithBag tells the query-builder to eager-load the nodes that are connected to
// the "bag" edge. The optional arguments are used to configure the query builder of the edge.
func (biq *BagItemQuery) WithBag(opts ...func(*BagQuery)) *BagItemQuery {
	query := &BagQuery{config: biq.config}
	for _, opt := range opts {
		opt(query)
	}
	biq.withBag = query
	return biq
}

// WithSubItems tells the query-builder to eager-load the nodes that are connected to
// the "sub_items" edge. The optional arguments are used to configure the query builder of the edge.
func (biq *BagItemQuery) WithSubItems(opts ...func(*SubItemQuery)) *BagItemQuery {
	query := &SubItemQuery{config: biq.config}
	for _, opt := range opts {
		opt(query)
	}
	biq.withSubItems = query
	return biq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BagItem.Query().
//		GroupBy(bagitem.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (biq *BagItemQuery) GroupBy(field string, fields ...string) *BagItemGroupBy {
	group := &BagItemGroupBy{config: biq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := biq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return biq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.BagItem.Query().
//		Select(bagitem.FieldName).
//		Scan(ctx, &v)
//
func (biq *BagItemQuery) Select(field string, fields ...string) *BagItemSelect {
	biq.fields = append([]string{field}, fields...)
	return &BagItemSelect{BagItemQuery: biq}
}

func (biq *BagItemQuery) prepareQuery(ctx context.Context) error {
	for _, f := range biq.fields {
		if !bagitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if biq.path != nil {
		prev, err := biq.path(ctx)
		if err != nil {
			return err
		}
		biq.sql = prev
	}
	return nil
}

func (biq *BagItemQuery) sqlAll(ctx context.Context) ([]*BagItem, error) {
	var (
		nodes       = []*BagItem{}
		withFKs     = biq.withFKs
		_spec       = biq.querySpec()
		loadedTypes = [2]bool{
			biq.withBag != nil,
			biq.withSubItems != nil,
		}
	)
	if biq.withBag != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, bagitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &BagItem{config: biq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, biq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := biq.withBag; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*BagItem)
		for i := range nodes {
			if fk := nodes[i].bag_items; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(bag.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "bag_items" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Bag = n
			}
		}
	}

	if query := biq.withSubItems; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[uuid.UUID]*BagItem)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.SubItems = []*SubItem{}
		}
		query.withFKs = true
		query.Where(predicate.SubItem(func(s *sql.Selector) {
			s.Where(sql.InValues(bagitem.SubItemsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.bag_item_sub_items
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "bag_item_sub_items" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "bag_item_sub_items" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.SubItems = append(node.Edges.SubItems, n)
		}
	}

	return nodes, nil
}

func (biq *BagItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := biq.querySpec()
	return sqlgraph.CountNodes(ctx, biq.driver, _spec)
}

func (biq *BagItemQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := biq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (biq *BagItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bagitem.Table,
			Columns: bagitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: bagitem.FieldID,
			},
		},
		From:   biq.sql,
		Unique: true,
	}
	if fields := biq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bagitem.FieldID)
		for i := range fields {
			if fields[i] != bagitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := biq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := biq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := biq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := biq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, bagitem.ValidColumn)
			}
		}
	}
	return _spec
}

func (biq *BagItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(biq.driver.Dialect())
	t1 := builder.Table(bagitem.Table)
	selector := builder.Select(t1.Columns(bagitem.Columns...)...).From(t1)
	if biq.sql != nil {
		selector = biq.sql
		selector.Select(selector.Columns(bagitem.Columns...)...)
	}
	for _, p := range biq.predicates {
		p(selector)
	}
	for _, p := range biq.order {
		p(selector, bagitem.ValidColumn)
	}
	if offset := biq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := biq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BagItemGroupBy is the group-by builder for BagItem entities.
type BagItemGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bigb *BagItemGroupBy) Aggregate(fns ...AggregateFunc) *BagItemGroupBy {
	bigb.fns = append(bigb.fns, fns...)
	return bigb
}

// Scan applies the group-by query and scans the result into the given value.
func (bigb *BagItemGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := bigb.path(ctx)
	if err != nil {
		return err
	}
	bigb.sql = query
	return bigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bigb *BagItemGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := bigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (bigb *BagItemGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(bigb.fields) > 1 {
		return nil, errors.New("ent: BagItemGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := bigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bigb *BagItemGroupBy) StringsX(ctx context.Context) []string {
	v, err := bigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bigb *BagItemGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = fmt.Errorf("ent: BagItemGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bigb *BagItemGroupBy) StringX(ctx context.Context) string {
	v, err := bigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (bigb *BagItemGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(bigb.fields) > 1 {
		return nil, errors.New("ent: BagItemGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := bigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bigb *BagItemGroupBy) IntsX(ctx context.Context) []int {
	v, err := bigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bigb *BagItemGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = fmt.Errorf("ent: BagItemGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bigb *BagItemGroupBy) IntX(ctx context.Context) int {
	v, err := bigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (bigb *BagItemGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(bigb.fields) > 1 {
		return nil, errors.New("ent: BagItemGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := bigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bigb *BagItemGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := bigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bigb *BagItemGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = fmt.Errorf("ent: BagItemGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bigb *BagItemGroupBy) Float64X(ctx context.Context) float64 {
	v, err := bigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (bigb *BagItemGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(bigb.fields) > 1 {
		return nil, errors.New("ent: BagItemGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := bigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bigb *BagItemGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := bigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bigb *BagItemGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = fmt.Errorf("ent: BagItemGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bigb *BagItemGroupBy) BoolX(ctx context.Context) bool {
	v, err := bigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bigb *BagItemGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range bigb.fields {
		if !bagitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := bigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bigb *BagItemGroupBy) sqlQuery() *sql.Selector {
	selector := bigb.sql
	columns := make([]string, 0, len(bigb.fields)+len(bigb.fns))
	columns = append(columns, bigb.fields...)
	for _, fn := range bigb.fns {
		columns = append(columns, fn(selector, bagitem.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(bigb.fields...)
}

// BagItemSelect is the builder for selecting fields of BagItem entities.
type BagItemSelect struct {
	*BagItemQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (bis *BagItemSelect) Scan(ctx context.Context, v interface{}) error {
	if err := bis.prepareQuery(ctx); err != nil {
		return err
	}
	bis.sql = bis.BagItemQuery.sqlQuery(ctx)
	return bis.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bis *BagItemSelect) ScanX(ctx context.Context, v interface{}) {
	if err := bis.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (bis *BagItemSelect) Strings(ctx context.Context) ([]string, error) {
	if len(bis.fields) > 1 {
		return nil, errors.New("ent: BagItemSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := bis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bis *BagItemSelect) StringsX(ctx context.Context) []string {
	v, err := bis.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (bis *BagItemSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bis.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = fmt.Errorf("ent: BagItemSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bis *BagItemSelect) StringX(ctx context.Context) string {
	v, err := bis.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (bis *BagItemSelect) Ints(ctx context.Context) ([]int, error) {
	if len(bis.fields) > 1 {
		return nil, errors.New("ent: BagItemSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := bis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bis *BagItemSelect) IntsX(ctx context.Context) []int {
	v, err := bis.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (bis *BagItemSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bis.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = fmt.Errorf("ent: BagItemSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bis *BagItemSelect) IntX(ctx context.Context) int {
	v, err := bis.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (bis *BagItemSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(bis.fields) > 1 {
		return nil, errors.New("ent: BagItemSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := bis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bis *BagItemSelect) Float64sX(ctx context.Context) []float64 {
	v, err := bis.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (bis *BagItemSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bis.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = fmt.Errorf("ent: BagItemSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bis *BagItemSelect) Float64X(ctx context.Context) float64 {
	v, err := bis.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (bis *BagItemSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(bis.fields) > 1 {
		return nil, errors.New("ent: BagItemSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := bis.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bis *BagItemSelect) BoolsX(ctx context.Context) []bool {
	v, err := bis.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (bis *BagItemSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bis.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{bagitem.Label}
	default:
		err = fmt.Errorf("ent: BagItemSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bis *BagItemSelect) BoolX(ctx context.Context) bool {
	v, err := bis.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bis *BagItemSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := bis.sqlQuery().Query()
	if err := bis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bis *BagItemSelect) sqlQuery() sql.Querier {
	selector := bis.sql
	selector.Select(selector.Columns(bis.fields...)...)
	return selector
}
