// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"web-stash-api/ent/predicate"
	"web-stash-api/ent/subitem"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubItemDelete is the builder for deleting a SubItem entity.
type SubItemDelete struct {
	config
	hooks    []Hook
	mutation *SubItemMutation
}

// Where adds a new predicate to the SubItemDelete builder.
func (sid *SubItemDelete) Where(ps ...predicate.SubItem) *SubItemDelete {
	sid.mutation.predicates = append(sid.mutation.predicates, ps...)
	return sid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sid *SubItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sid.hooks) == 0 {
		affected, err = sid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SubItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sid.mutation = mutation
			affected, err = sid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sid.hooks) - 1; i >= 0; i-- {
			mut = sid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sid *SubItemDelete) ExecX(ctx context.Context) int {
	n, err := sid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sid *SubItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: subitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: subitem.FieldID,
			},
		},
	}
	if ps := sid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sid.driver, _spec)
}

// SubItemDeleteOne is the builder for deleting a single SubItem entity.
type SubItemDeleteOne struct {
	sid *SubItemDelete
}

// Exec executes the deletion query.
func (sido *SubItemDeleteOne) Exec(ctx context.Context) error {
	n, err := sido.sid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sido *SubItemDeleteOne) ExecX(ctx context.Context) {
	sido.sid.ExecX(ctx)
}
