// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bag is the predicate function for bag builders.
type Bag func(*sql.Selector)

// BagItem is the predicate function for bagitem builders.
type BagItem func(*sql.Selector)

// Share is the predicate function for share builders.
type Share func(*sql.Selector)

// SubItem is the predicate function for subitem builders.
type SubItem func(*sql.Selector)
